version: '2'
services:
  sam-api-gateway:
    build: .
    #image: davsanba/sam-api-gateway
    command: bash -c "sleep 40 && rm -f tmp/pids/server.pid && bundle exec rails s -p 4001 -b '0.0.0.0'"
    ports:
      - "4001:4001"
    environment:
      - SANTIAGO="http://192.168.43.43:"
      - REG="http://192.168.99.103:"
      - SESS="http://192.168.99.101:"
      - PROG="http://192.168.99.103:"
      - LDAP="http://192.168.43.43:"
